### ISSUE TITLE
安装按钮不可以操作~~~~~

### ISSUE THREAD

**Issue by 5718KB** [alfiecg24/TrollInstallerX#13]
**iPad Air2 15.8.2

试了所有的办法，最后的希望就是你，为什么安装按钮不能点亮**

![Uploading IMG_0002.PNG…]()

**Comment by alfiecg24** [comment]
iPad Air 2 isn’t supported for the time being.

**Comment by 5718KB** [comment]
> 暂时不支持iPad Air 2。

之后有希望么，现在没有任何软件支持。。。。
