### ISSUE TITLE
trollinstallerx wont download

### ISSUE THREAD

**Issue by BabyAPF** [alfiecg24/TrollInstallerX#20]
ive tried multiple times to download the .ipa file but the download keeps getting restricted due to containing viruses
![screenshot-nimbusweb_me-2024_06_14-09_07_18](https://github.com/alfiecg24/TrollInstallerX/assets/121609459/5a3921db-9d95-4b60-a4da-f9b027048d69)

**Comment by alfiecg24** [comment]
Disable real-time protection in Windows Defender and your browser’s download security settings if necessary.
