### ISSUE TITLE
a13 15.7.2

### ISSUE THREAD

**Issue by cdK1337** [alfiecg24/TrollInstallerX#21]
I'm on iPhone SE 2020, iOS 15.7.2 (I know this version haven't been released officially for this phone, installed via OTA + Some other things, don't remember). Trollstore doesn't install via TrollinstallerX. It says: 

Running on an iPhone12,8 on iOS 15.7.2

Downloading kernel

libgrabkerne12: ERROR: Failed to find a firmware URL!
libgrabkerne12: ERROR: Failed to get a firmware URL!
Failed to download kernel

Failed to get kernel

I tried to reboot by phone, clear cached kernel, landa-physpuppet - didn't help, unfortunately.

**Comment by alfiecg24** [comment]
My apologies, please test [this IPA}(https://www.swisstransfer.com/d/3068fc5f-c5c7-491c-99c9-cf43591c92d8) and let me know whether it can download the kernel correctly.

**Comment by cdK1337** [comment]
> My apologies, ~please test [this IPA](https://www.swisstransfer.com/d/3068fc5f-c5c7-491c-99c9-cf43591c92d8)~ and let me know whether it can download the kernel correctly.
> 
> Edit: use [this one](https://www.swisstransfer.com/d/d787d4f1-5b80-4760-9a1f-2a7e55306114) instead.

Hello, it stucks on "Downloading kernel" (tried landa and physpuppet)

**Comment by alfiecg24** [comment]
The fact that it fails to fetch the API data is unlikely to be related to TrollInstallerX. Are you able to download https://api.appledb.dev/ios/main.json.xz in Safari?

**Comment by cdK1337** [comment]
> The fact that it fails to fetch the API data is unlikely to be related to TrollInstallerX. Are you able to download https://api.appledb.dev/ios/main.json.xz in Safari?

When i paste it, I receive a notification: "Do you want to download "main.json.xz"?". Press download - and it downloads it

**Comment by alfiecg24** [comment]
Have you changed networks at all since trying TrollInstallerX? Could you try again?

**Comment by cdK1337** [comment]
> Have you changed networks at all since trying TrollInstallerX? Could you try using it again?

Yes, I've tried different networks and vpns, same issue 
Could you add verbose log, to see what's going on? So I will send you it 
"Failed to fetch api" happened, because my vpn went down

**Comment by alfiecg24** [comment]
I don't believe this is an issue with TrollInstallerX. There isn't really much more logging I can add, but when I changed libgrabkernel2 to think it is running iOS 15.7.2 (on iPhone12,8) it was able to download the kernelcache without issue.

**Comment by TWNFFW** [comment]
> 我不认为这是 TrollInstallerX 的问题。我真的没有更多可以添加的日志记录，但是当我更改 libgrabkernel2 以认为该设备运行的是 iOS 15.7.2（它也是 iPhone12,8）时，它能够毫无问题地下载 kernelcache。

Running on an ipad8.10（A12Z） on ios 15.7.2 ----- The kernel was successfully downloaded
Running on an iphone11.2（A12） on ios 15.7.2 ----- got “Downloading kernel”
