### ISSUE TITLE
 Xcode15.4 compilation error

### ISSUE THREAD

**Issue by guotaoeunke** [alfiecg24/TrollInstallerX#25]
Hello, I used Xcode15.4 to compile, and the error message was prompted: XPC module is repeatedly defined.
![Snip20240723_3](https://github.com/user-attachments/assets/b9838e5f-e517-416c-abe3-bcf136971762)

**Comment by alfiecg24** [comment]
Sorry for not getting back to you sooner, but as of the next release of TrollInstallerX (1.0.3), it will only be compilable by default on Xcode 15.4+ (fixing your issue). Anyone on a lower version will need to add the XPC headers themselves.
