### ISSUE TITLE
assertion failed?

### ISSUE THREAD

**Issue by guotaoeunke** [alfiecg24/TrollInstallerX#26]
The red mark indicates that the assertion failed. Is it a kernel error? and how to solve?
![WechatIMG255](https://github.com/user-attachments/assets/5d205fae-22c5-40a4-a7e6-2409c04feb1d)

**Comment by alfiecg24** [comment]
Shut down your device and turn it back on again.

**Comment by guotaoeunke** [comment]
> Shut down your device and turn it back on again.

thank you
