### ISSUE TITLE
Yellow iPhone 14 or Yellow iPhone 14 Plus on iOS 16.3 (20D50)

### ISSUE THREAD

**Issue by En2024en** [alfiecg24/TrollInstallerX#33]
Yellow iPhone 14 or Yellow iPhone 14 Plus on iOS 16.3 (20D50)

I have this device , can't able to install troll installerx  getting error " 
![IMG_0001](https://github.com/user-attachments/assets/e7127740-b909-454d-8fc6-d1712d928884)
failed to download kernel "

**Comment by En2024en** [comment]
FINALLY its done by this https://trollstore.app/installing-trollhelper-misaka/

**Comment by alfiecg24** [comment]
For future reference, [this](https://www.swisstransfer.com/d/433d181a-d35f-423e-91e4-1cc6a4edbe65) build should work. Is there any chance you could test, please? Thank you!
