### ISSUE TITLE
fail to install，here is the message，my device is iPhone7 ios15.8.1

### ISSUE THREAD

**Issue by iponkan** [alfiecg24/TrollInstallerX#6]
![image](https://github.com/alfiecg24/TrollInstallerX/assets/8266111/13fab298-c566-43d5-9136-20f930acf3c3)
my iPhone6s ios15.8.1 also have this problem.

**Comment by ihwf** [comment]
I have the same issue, so how to resolve it?

**Comment by iponkan** [comment]
> I have the same issue, so how to resolve it?

network problem

**Comment by ihwf** [comment]
thanks

**Comment by 5718KB** [comment]
**ipad air2   15.8.2

试了所有的办法，最后的希望就是你，为什么安装按钮不能点亮**

![IMG_0002](https://github.com/alfiecg24/TrollInstallerX/assets/166584985/cbea4049-a5d1-4dd5-93b6-9aa3b70fc553)
